name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }} && \
          docker build -t ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }} . && \
          docker push ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd scripts
            sudo docker ps -a -q --filter "name=gateway" | grep -q . && docker stop gateway && docker rm gateway | true
            sudo docker rmi ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            docker run -d -p 8080:8080 --env-file=env_list.txt --name gateway ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            docker rmi -f $(docker images -f "dangling=true" -q) || true